/**
 * Web Automation Core (HARPA-style DOM Engine)
 * Parses JSON action arrays generated by AI and executes them natively in the browser.
 * Supports click, type, navigate, wait, extract, scroll, hover, select, keyboard, condition.
 */

export interface DOMAction {
  action: 'click' | 'type' | 'navigate' | 'wait' | 'extract' | 'scroll' | 'hover' | 'select' | 'keyboard' | 'condition';
  selector?: string;
  value?: string;
  url?: string;
  ms?: number;
  y?: number; // For scroll: pixels from top, or relative amount
  key?: string; // For keyboard action
  modifiers?: string[]; // For keyboard: ['ctrl', 'shift']
  expect?: string; // For condition: text to expect
  continueOnError?: boolean;
}

export interface AutomationResult {
  action: string;
  success: boolean;
  output: string;
}

function delay(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function findElement(selector: string): Element | null {
  try {
    return document.querySelector(selector);
  } catch {
    return null;
  }
}

function isVisible(el: Element): boolean {
  const rect = (el as HTMLElement).getBoundingClientRect();
  const style = window.getComputedStyle(el);
  return (
    rect.width > 0 &&
    rect.height > 0 &&
    style.display !== 'none' &&
    style.visibility !== 'hidden' &&
    style.opacity !== '0'
  );
}

export async function executeDOMAction(actionObj: DOMAction): Promise<AutomationResult> {
  const { action, selector, value, url, ms, y, key, modifiers, expect, continueOnError: _ } = actionObj;

  switch (action) {
    case 'click': {
      if (!selector) return { action, success: false, output: 'Click requires a selector.' };
      const btn = findElement(selector) as HTMLElement;
      if (!btn) return { action, success: false, output: `Element not found: ${selector}` };
      if (!isVisible(btn)) return { action, success: false, output: `Element not visible: ${selector}` };
      // Dispatch full pointer event sequence for compatibility with React/Vue/Angular
      btn.focus();
      ['pointerdown', 'mousedown', 'pointerup', 'mouseup', 'click'].forEach(ev => {
        btn.dispatchEvent(new MouseEvent(ev, { bubbles: true, cancelable: true }));
      });
      btn.click();
      return { action, success: true, output: `Clicked: ${selector}` };
    }

    case 'type': {
      if (!selector || value === undefined) return { action, success: false, output: 'Type requires selector and value.' };
      const input = findElement(selector) as HTMLInputElement | HTMLTextAreaElement;
      if (!input) return { action, success: false, output: `Input not found: ${selector}` };
      input.focus();
      // Clear first
      input.value = '';
      input.dispatchEvent(new Event('input', { bubbles: true }));
      // Set value
      input.value = value;
      // Try execCommand for React-controlled inputs
      try {
        const nativeInputSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value')?.set ||
          Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, 'value')?.set;
        nativeInputSetter?.call(input, value);
      } catch { /* ignore */ }
      input.dispatchEvent(new InputEvent('input', { bubbles: true, inputType: 'insertText', data: value }));
      input.dispatchEvent(new Event('change', { bubbles: true }));
      return { action, success: true, output: `Typed "${value}" into: ${selector}` };
    }

    case 'navigate': {
      if (!url) return { action, success: false, output: 'Navigate requires a URL.' };
      if (!url.startsWith('http://') && !url.startsWith('https://')) {
        return { action, success: false, output: `Invalid URL (must start with http/https): ${url}` };
      }
      window.location.href = url;
      return { action, success: true, output: `Navigating to: ${url}` };
    }

    case 'wait': {
      const waitMs = Math.min(ms || 1000, 10000); // Max 10s wait
      await delay(waitMs);
      return { action, success: true, output: `Waited ${waitMs}ms` };
    }

    case 'extract': {
      if (!selector) return { action, success: false, output: 'Extract requires a selector.' };
      const el = findElement(selector);
      if (!el) return { action, success: false, output: `Element not found: ${selector}` };
      const text = (el.textContent || (el as HTMLInputElement).value || '').trim();
      const truncated = text.length > 5000 ? text.substring(0, 5000) + '...' : text;
      return { action, success: true, output: `Extracted from ${selector}: ${truncated}` };
    }

    case 'scroll': {
      if (selector) {
        const el = findElement(selector);
        if (el) {
          el.scrollIntoView({ behavior: 'smooth', block: 'center' });
          return { action, success: true, output: `Scrolled to: ${selector}` };
        }
      }
      const scrollTo = y !== undefined ? y : window.scrollY + 500;
      window.scrollTo({ top: scrollTo, behavior: 'smooth' });
      return { action, success: true, output: `Scrolled to y=${scrollTo}` };
    }

    case 'hover': {
      if (!selector) return { action, success: false, output: 'Hover requires a selector.' };
      const el = findElement(selector) as HTMLElement;
      if (!el) return { action, success: false, output: `Element not found: ${selector}` };
      ['pointerover', 'pointerenter', 'mouseover', 'mouseenter'].forEach(ev => {
        el.dispatchEvent(new MouseEvent(ev, { bubbles: true, cancelable: true }));
      });
      return { action, success: true, output: `Hovered: ${selector}` };
    }

    case 'select': {
      if (!selector || !value) return { action, success: false, output: 'Select requires selector and value.' };
      const sel = findElement(selector) as HTMLSelectElement;
      if (!sel) return { action, success: false, output: `Select element not found: ${selector}` };
      // Try matching by value or text
      const option = Array.from(sel.options).find(o => o.value === value || o.text === value);
      if (!option) return { action, success: false, output: `Option "${value}" not found in ${selector}` };
      sel.value = option.value;
      sel.dispatchEvent(new Event('change', { bubbles: true }));
      return { action, success: true, output: `Selected "${value}" in: ${selector}` };
    }

    case 'keyboard': {
      if (!key) return { action, success: false, output: 'Keyboard requires a key.' };
      const target = (selector ? findElement(selector) : document.activeElement) as HTMLElement || document.body;
      const opts: KeyboardEventInit = {
        key,
        bubbles: true,
        cancelable: true,
        ctrlKey: modifiers?.includes('ctrl'),
        shiftKey: modifiers?.includes('shift'),
        altKey: modifiers?.includes('alt'),
        metaKey: modifiers?.includes('meta'),
      };
      target.dispatchEvent(new KeyboardEvent('keydown', opts));
      target.dispatchEvent(new KeyboardEvent('keyup', opts));
      return { action, success: true, output: `Key pressed: ${modifiers?.join('+') || ''}${key}` };
    }

    case 'condition': {
      if (!selector) return { action, success: false, output: 'Condition requires a selector.' };
      const el = findElement(selector);
      if (!el) return { action, success: false, output: `Condition FAILED: Element not found: ${selector}` };
      if (expect) {
        const text = el.textContent?.trim() || '';
        if (!text.includes(expect)) {
          return { action, success: false, output: `Condition FAILED: Expected "${expect}" in "${text.substring(0, 100)}"` };
        }
      }
      return { action, success: true, output: `Condition met: ${selector}${expect ? ` contains "${expect}"` : ' exists'}` };
    }

    default:
      return { action, success: false, output: `Unknown action: ${action}` };
  }
}

export async function runAutomationSequence(actions: DOMAction[]): Promise<string[]> {
  const results: string[] = [];
  for (const act of actions) {
    try {
      const res = await executeDOMAction(act);
      results.push(res.success ? `✅ ${res.output}` : `❌ ${res.output}`);
      // Halt on failure unless continueOnError is set
      if (!res.success && !act.continueOnError) break;
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      results.push(`❌ Error in ${act.action}: ${msg}`);
      if (!act.continueOnError) break;
    }
  }
  return results;
}

export function parseAIActions(text: string): DOMAction[] | null {
  try {
    // Match JSON array in markdown code blocks (with or without language tag)
    const jsonMatch = text.match(/```(?:json)?\s*(\[[\s\S]*?\])\s*```/);
    const jsonStr = jsonMatch ? jsonMatch[1] : text.trim();

    // Only attempt parse if it looks like JSON array
    if (!jsonStr.startsWith('[')) return null;

    const actions = JSON.parse(jsonStr);
    if (Array.isArray(actions) && actions.length > 0 && typeof actions[0].action === 'string') {
      return actions as DOMAction[];
    }
  } catch {
    // Not valid JSON
  }
  return null;
}

// ── Automation Templates ──

export const AUTOMATION_TEMPLATES: { name: string; description: string; actions: DOMAction[] }[] = [
  {
    name: 'Accept Cookie Banner',
    description: 'Clicks common cookie accept buttons',
    actions: [
      { action: 'click', selector: '#accept-cookies, .accept-cookies, [id*="cookie"][id*="accept"], [class*="cookie"][class*="accept"], #CybotCookiebotDialogBodyButtonAccept', continueOnError: true },
      { action: 'click', selector: '[aria-label*="Accept"], button:has-text("Accept All"), .cc-allow', continueOnError: true },
    ],
  },
  {
    name: 'Scroll to Bottom',
    description: 'Scroll to page bottom and back',
    actions: [
      { action: 'scroll', y: 999999 },
      { action: 'wait', ms: 1000 },
    ],
  },
  {
    name: 'Extract All Links',
    description: 'Extract all links from the page',
    actions: [
      { action: 'extract', selector: 'body' },
    ],
  },
  {
    name: 'Click Next Page',
    description: 'Navigate to next page in paginated content',
    actions: [
      { action: 'click', selector: '[aria-label="Next page"], .next-page, a[rel="next"], .pagination .next, button:last-child[class*="pag"]', continueOnError: true },
      { action: 'wait', ms: 1500 },
    ],
  },
  {
    name: 'Close Modal / Popup',
    description: 'Close common modal dialogs and popups',
    actions: [
      { action: 'keyboard', key: 'Escape' },
      { action: 'click', selector: '[aria-label="Close"], .close-btn, .modal-close, [class*="close"][class*="modal"], .dismiss', continueOnError: true },
    ],
  },
];
